### ISSUE TITLE
临时解决方法也没法用吧

### ISSUE THREAD

**Issue by ekee** [jsthon/Flarum-zh-CN#2]
临时解决方法也没法用吧，除了安装的时候替换，缓存都不能乱删。。。

**Comment by jsthon** [comment]
请删除缓存 /flarum/assets (保留目录下的 avatars 与 fonts)

**Comment by ekee** [comment]
好的，原来那才是缓存啊，flarum 现在beta貌似不能直接用，不知道什么时候能真正用起来。话说他们开发怎么开发的，我看都是搞js，完全无法融入。中文不像英文用空格隔断，中文搜索也还是一整串中文才能搜索，这点不懂怎样才能完美。

**Comment by jsthon** [comment]
现在刚发布 Flarum beta 测试版本还不是很完善，日后将改善。

**Comment by ekee** [comment]
中文搜索那点我估计永远无法改善，不过话说国产论坛中文搜索也不是很强
